# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ad45f7f08336b5a2210ad4110f0da4f9bb175654e4a59ab55a7313c7ab5a4034a4712cf8e28e3373b74ed9cd767e7a2097264fd24a48eab4c3a12a2b35e75c

test:
  secret_key_base: bc8f6e866cc004a6354269eee684fc3fe306320b541e34707bbd8dceed3001d440e85a1add7034acc631c8f507b48dbbf9f6ce05da3668b1713c89fb1e478b73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
